# Autocoder - Usage Template
# This is an example pipeline template showing how to use the Autocoder task

parameters:
  - name: workItemId
    type: string
    displayName: 'Work Item ID'
    default: ''

  - name: agentType
    type: string
    displayName: 'AI Agent'
    default: 'copilot'
    values:
      - copilot
      - claude

  - name: userPrompt
    type: string
    displayName: 'User Prompt'
    default: ''

  - name: createPullRequest
    type: boolean
    displayName: 'Create Pull Request'
    default: true

  - name: targetBranch
    type: string
    displayName: 'Target Branch'
    default: 'main'

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: autocoder-secrets  # Contains GITHUB_PAT and CLAUDE_API_KEY

stages:
  - stage: Generate
    displayName: 'Generate Code'
    jobs:
      - job: Autocoder
        displayName: 'Run Autocoder'
        steps:
          - checkout: self
            persistCredentials: true
            fetchDepth: 0

          - task: Autocoder@1
            displayName: 'Execute AI Agent'
            inputs:
              workItemId: '${{ parameters.workItemId }}'
              agentType: '${{ parameters.agentType }}'
              userPrompt: '${{ parameters.userPrompt }}'
              createPullRequest: '${{ parameters.createPullRequest }}'
              targetBranch: '${{ parameters.targetBranch }}'
            env:
              GITHUB_PAT: $(GITHUB_PAT)
              CLAUDE_API_KEY: $(CLAUDE_API_KEY)
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)

          - script: |
              echo "Autocoder completed!"
              echo "Pull Request URL: $(AutocoderPullRequestUrl)"
            displayName: 'Display Results'
            condition: and(succeeded(), eq('${{ parameters.createPullRequest }}', true))
